from pydantic_ai import Agent, RunContext
import logfire
from llm import *
import sqlite3
from config_reader import *
from dependencies import *


def run_sql_tool(ctx: RunContext[Deps], sql_query: str) -> list[tuple]:
    """Run sql query on the database

    Args:
        ctx: The context.
        sql_query: The generated sql query.
    """
    logfire.info(f"sql query generated by model:{sql_query}")
    try:
        with sqlite3.connect(ctx.deps.db_file_path) as conn:
            cursor = conn.cursor()
            cursor.execute(sql_query)
            results = cursor.fetchall()
            return results
    except Exception as e:
        print(e)
    return []


def create_sql_executor_agent():
    model = build_model(
        model_name=settings.llm_executor.name,
        api_key=settings.llm_executor.api_key,
        base_url=settings.llm_executor.base_url,
        temperature=settings.llm_executor.temperature,
        max_tokens=settings.llm_executor.max_tokens,
    )
    sql_executor_agent = Agent(
        model=model,
        instructions=settings.llm_executor.prompt,
        deps_type=Deps,
        tools=[run_sql_tool],
        retries=3,
    )
    return sql_executor_agent
